### ISSUE TITLE
Implement Tabular Preview for Dataset Details Page

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#171] opened 2024-10-22 14:44 UTC
As a user of the TDC portal, I want to preview tabular data within the dataset details page, so that I can get an overview of the data before deciding whether to download or interact with it.

## Tasklist (TBD - to be updated by the developer)
* [add data]

## Acceptance Criteria
Given that I am viewing the details page of a dataset with structured data uploaded to the db,
* [ ] I can see a preview of the dataset when i go to the dataset's details page and open the "dataset" tab
* [ ] I can view the tabular preview on the portal without having to download the dataset first
* [ ] the tabular preview should load up quickly for me 
* [ ] while the preview is loading up, I can see a loading indicator in the preview window

**Comment by luccasmmg** [comment] 2024-10-25 12:15
A couple of thoughts on this 

Demenech idea of what you guys want being a pivot table makes sense, what i did was that i grabbed that CSV, added a couple of integer columns and checked how it looked on google sheets and it seems to work 
![image](https://github.com/user-attachments/assets/e780a97a-3695-4d4d-84e2-c3b3f4b5c935)

After that i loaded the csv into a sql database and started looking into how we could retrieve the data, shouldnt be too hard with something like this, the main tricky part is that we need to retrieve all the possible values for the column field, so in this example before we build the query we need to fetch all possible values for the `Time` column
![image](https://github.com/user-attachments/assets/94445ce9-3458-42e5-9326-d3a445d5ec30)

One thing to keep in mind is that we are assuming that even tough in the mockup `Columns` and `Rows` and `Values` are in the plural, we think its better to simplify things and only have the user be able to select one of each, selecting multiple of those would greatly complicate things without much benefit (After all the user can always just download the csv and put it in whateaver tool he wants)

One weird thing in the mockup is that here it appears as if multiple values are being selected, even tough the table only shows one, which leads me to believe that these are actually filters, which we can of course implement
![image](https://github.com/user-attachments/assets/9646fdc6-a992-4def-ae27-a0ccab8098f6)

This is for example the same sql for the pivot table, but filtering by the column `Service` = `Passenger`
![image](https://github.com/user-attachments/assets/56ff170a-2cfe-4eaf-a1b4-9260d28a8030)

One final thing is that the mockup doesnt seem to provide a way to select the aggregation function that is going to be used, for example, the values could be joined by `Sum` by `Mean` by `Aggregate` by `Count` etc

Besides that these dropdowns altough they make sense if we are talking about filters, they do not seem to make sense when it comes to the `Columns` and `Rows` sections

![image](https://github.com/user-attachments/assets/0a2a41bd-d22b-42a2-adfd-456835b466ee)

This is for the table preview as a whole, leaving a comment below about the footnotes

**Comment by luccasmmg** [comment] 2024-10-25 12:21
I want to talk about this footnotes here
![image](https://github.com/user-attachments/assets/f53f5c6e-c7b6-432a-9e26-e5acd3b88091)

If we are understanding the data correctly, essentially what we have here is 

Give me an aggregation of X value for every row in which the country is `Afeghanistan` and the time is `1998` which in by looking at the table would mean something like this

![image](https://github.com/user-attachments/assets/b538a646-dc16-47d2-b7fe-feec0d7fbb01)

As you can see, we have 4 rows, each with potentially 4 different metadata fields, we cant really join together text in a way that makes sense, so the only logical way to choose one of those 4 is to grab the first one, unless there is some other way i cant think of something better, any thoughts?

**Comment by luccasmmg** [comment] 2024-10-25 12:23
Finally i think this dropdown would be better of not being done, given the deadline and the fact that it doesnt seem to provide that much more clarity and the fact that i expect quite a few issues related to it
![image](https://github.com/user-attachments/assets/77297f0b-5400-4023-b8ea-b58974aab179)

**Comment by luccasmmg** [comment] 2024-10-25 12:27
As shown in these comments i think the main contraints that we should follow is 

1. Single column between the available ones
2. Single row between the available ones
3. Single value between the available ones
4. Multiple filters, which i think would be better if we used an UI like this one, which is more powerful and we already have most of the code for it
![image](https://github.com/user-attachments/assets/89bbad6a-39ba-4311-ae61-2cef41644c95)
5. Unless provided with a better solution, to use the first possible value for the metadata popup

**Comment by khaeru** [comment] 2024-10-30 09:14
Hi—asked to jump in here by @nicolas-becker:

Briefly, what I do not find in this thread is any mention of or engagement with existing tooling that could be used to provide these parts of the UX.

The visual prototype and written requirements for these features are almost entirely based on users' experience with existing software, for instance the [Eurostat Data Browser](https://ec.europa.eu/eurostat/databrowser/product/view/avia_if_typ) and similar. Many of these are Free Software.

To me it does not make sense to:
1. Look at/using existing tools.
2. Derive from (1) certain requirements.
3. Ignore (1), and write new code from scratch to implement (2).

I have seen a lot of organizations do this; it creates technical debt, maintenance burden, and products that are less functional than the ones that inspired them (1).

I think it would be much more valuable to:
- Survey widely for existing tooling and applications that can be used to implement these features.
- Provide a detailed technical assessment of these, including:
  - How easy or hard it would be to integrate them with TDC CKAN.
  - Which of the desired features they appear to have, or lack.
  - What would be the work required to integrate; implement missing features; and maintain.
- Recommend one or a few options to be pursued.

I think we should strenuously avoid to end the project with a limited/partial hack at (3) (whatever is possible within the budget/time allocated) that TDCI is then forced to invest heavily to maintain or extend to feature-completeness; and at the same time no progress towards integration and reuse of higher-quality code.

**Comment by osahon-okungbowa** [comment] 2024-10-30 09:29
@khaeru given tyour response in this ticket, I strongly advise/recommend that you attend our meeting(s) moving forward. It would be more productive to have you there while discussions/analyses are being had.
Reason for this request:
- we were unaware of any sort of relationship/similarity with the Eurostat Browser you referenced during our discussions on this.

given this new information, we will have to re-evaluate/re-analyse (this is far from ideal) to see what is possible given this project's limited scope and budget.

**Comment by khaeru** [comment] 2024-10-30 09:42
> I strongly advise/recommend that you attend our meeting(s) moving forward. It would be more productive to have you there while discussions/analyses are being had.

Hi Osahon —I would also like this. Unfortunately, because the TDCI is itself limited in resources, I am participating largely on a volunteer basis. (For a *different* TDCI project transport-data/tools#21 etc. my participation is partially funded, but that time must be used towards that project's deliverables.) I already have about 2 hours of weekly meetings+prep for TDCI activities, which is about as much as I can accommodate given my actual job. Because I know that Verena and Nicolas are working hard to give you & team the info and guidance you need, I have tried to jump in when they ask, and otherwise not.

I would propose that you and they identify each week whether my presence is critical or not at such meetings, and then let me know. I would then try to clear the time on my side.

**Comment by luccasmmg** [comment] 2024-10-30 11:28
@khaeru can you at least get me the repo for the Eurostat Data Browser?

Assuming that we do what you are suggesting we would need to probably 

1. Grab the repo, which im assuming is going to be for the entire website, not just the section which visualizes individual pieces of data
2. Try to extract that piece of code into something that can be used by our portal
3. Remove everything related to the eurostat backend so that it points to the ckan backend
4. Start adapting things that dont make sense or are limited by CKAN itself 
5. Insert this fork of one section of the Eurostat Data Browser into our own portal

**Comment by khaeru** [comment] 2024-10-30 12:17
Back in 2022 TDCI participants brainstormed a list of [Existing transport data tools, processes, etc.](https://docs.google.com/document/d/1Zd_lxQYotJOL_ioczHlaFyPpR5p-1Dy_/edit) that includes the (then-current) link to the Eurostat distribution of "REDISSTAT". It's on some "Interoperable EU" platform (maybe the EU is averse to U.S.-owned GitHub?) and not recently updated. I think a first step would be contacting Eurostat to ask where the current version is.

@Verena205 also conducted an extensive series of interviews with representatives of the different organizations mentioned. IIRC that turned up further candidates, like:
- https://github.com/OCHA-DAP —tools behind https://data.humdata.org
- https://github.com/owid —behind https://ourworldindata.org

…among maybe others. I am not sure where those interview notes or summary are in the TDC Google Drive, but @nicolas-becker or Verena should be able to locate them for you.

> Assuming that we do what you are suggesting we would need to probably

Please see again where I wrote “I think it would be much more valuable to…”

The key point is that **we don't know** whether the Eurostat tool, or some other, or nothing, provides the most suitable (most easily reusable/integrated, clearly documented, actively maintained etc.) components for the functionality TDC needs. (We **do know** that its functionality is more or less what we want, but mashing it together with CKAN may be more trouble than it's worth.)

So I'm *not* suggesting we do the 5 things in your list. But the fact that you can *make* such a list —i.e. that you can clearly envision the work involved— IMHO shows that you/Datopian have the skills and experience to do the assessment that I *am* suggesting.

The outcome of such an assessment might be one of:
- Some of the orgs/platforms surveyed by TDC provide components we can reuse: the best are X, Y, Z.
- None of the above is suitable, but we found other components that integrate well with CKAN and TDCI's SDMX-based data processes, and can provide the functionality needed.
- Nothing suitable exists, we will have to build something from scratch and maintain it.

If it turns out to be the last one, that would be unfortunate, but then we at least would know for sure that we need to get TDCI funders to pay for that work (both up-front and ongoing).

**Comment by luccasmmg** [comment] 2024-11-05 12:42
@khaeru i finished checking that docs and apart from the ones you mentioned in your comment, the most promissing one was the Stat Data Explorer(https://gitlab.com/sis-cc/.stat-suite/dotstatsuite-data-explorer) unfurtonately that is a full fledged solution, with search browse and so on, so its would be the equivalent of the entire CKAN instance, with that in mind we are most likely going with the original approach of building a simple component reusable component that can fetch data from ckan datastore

**Comment by luccasmmg** [comment] 2024-11-11 13:31
docs : https://github.com/transport-data/tdc-data-portal/blob/main/docs/datasets/README.md#tdc-harmonized-preview
sample dataset: https://tdc-data-portal.vercel.app/@sample-org/dataset-with-everything

**Comment by Uchechukwu-Onye-Igbo** [comment] 2024-11-12 08:19
Hi @luccasmmg this looks good. tested it again and it works right. Good work

**Comment by nicolas-becker** [comment] 2024-11-12 10:29
Hi @luccasmmg , thank you, this is already close to what we want. 

What is missing here is the connection to the SDMX data structure definition. As you remember, this pivot-like visualization was intended only for SDMX compliant data sources and should be agnostic/adaptable to any SDMX compliant data structure, in the same way. The data structure definition defines the list of dimensions, including their order, IDs, names, descriptions, and the code lists to be used for each one. In our case, we use a reduced SDMX version, as was provided to @demenech when he built the data model.

So to be clear, we want all data views for TDC Formatted and TDC Harmonized data to receive structure information from the SDMX information model. This way, we know how we want the data to be visualized, or more specifically which of the fields contains:

- `Indicators` (also refered to as `Measures`): describing the information measures in the data set. In the example we have 3 different indicators (Transport activity, Vehicle stock in use (VS), Cumulative vehicle registration)
- `Observations`: containing the value for the measures. In this case this would be the "Observation value", as you correctly displayed.
- `Dimensions`: an arbitrary number of dimensions which are to be displayed as rows, columns or further filters. The user can choose which dimensions are displayed in which way, just like you implemented it. In this example, the dimensions would be: Sector, Service, Vehicle Category, Scope, Geography, Fuel, Time.
- Further metadata `Attributes` to be displayed in the context menu. In this case we have the Source, the Primary source, Unit, and the Metadata field. These are to be displayed in the context window for each data point (just as you currently visualize the Metadata field. See also again the Figma example for this.)

As stated in my comment [here](https://github.com/transport-data/tdc-data-portal/issues/166#issuecomment-2460390659) (issue #166) the SDMX converted version of GFEI data should be a great opportunity to this functionality.

I hope this further explanation is clear. Please reach out if you need further guidance, we can also have a specific call on this if you prefer.

**Comment by luccasmmg** [comment] 2024-11-12 10:32
> Hi @luccasmmg , thank you, this is already close to what we want. 
> 
> What is missing here is the connection to the SDMX data structure definition. As you remember, this pivot-like visualization was intended only for SDMX compliant data sources and should be agnostic/adaptable to any SDMX compliant data structure, in the same way. The data structure definition defines the list of dimensions, including their order, IDs, names, descriptions, and the code lists to be used for each one. In our case, we use a reduced SDMX version, as was provided to @demenech when he built the data model.
> 
> So to be clear, we want all data views for TDC Formatted and TDC Harmonized data to receive structure information from the SDMX information model. This way, we know how we want the data to be visualized, or more specifically which of the fields contains:
> 
> - `Indicators` (also refered to as `Measures`): describing the information measures in the data set. In the example we have 3 different indicators (Transport activity, Vehicle stock in use (VS), Cumulative vehicle registration)
> - `Observations`: containing the value for the measures. In this case this would be the "Observation value", as you correctly displayed.
> - `Dimensions`: an arbitrary number of dimensions which are to be displayed as rows, columns or further filters. The user can choose which dimensions are displayed in which way, just like you implemented it. In this example, the dimensions would be: Sector, Service, Vehicle Category, Scope, Geography, Fuel, Time.
> - Further metadata `Attributes` to be displayed in the context menu. In this case we have the Source, the Primary source, Unit, and the Metadata field. These are to be displayed in the context window for each data point (just as you currently visualize the Metadata field. See also again the Figma example for this.)
> 
> As stated in my comment [here](https://github.com/transport-data/tdc-data-portal/issues/166#issuecomment-2460390659) (issue #166) the SDMX converted version of GFEI data should be a great opportunity to this functionality.
> 
> I hope this further explanation is clear. Please reach out if you need further guidance, we can also have a specific call on this if you prefer.

I don't think I understand can you be more concrete, essentially send a bunch of screenshots of sections of the preview and say "This should show X, it now shows Y"?

**Comment by nicolas-becker** [comment] 2024-11-12 14:51
@luccasmmg sure. But please keep in mind that the solution should be generally applicable to any SDMX compliant data set on the platform and not tailored to the specifics of the provided example data set. 

I will refer to the [SDMX version of the GFEI data set](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzenodo.org%2Frecords%2F14046031&data=05%7C02%7Cnicolas.becker%40giz.de%7C3362a9899ee345e6ea9608dcfe682a77%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C638664970564651154%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=BnlKvG2B7QlhZBjkSrpl3h4GcjpONwG3%2F%2BzbMr82%2BqE%3D&reserved=0) again. Here you'll find a zip file containing 6 XML files. Five of them contain the data flows themselves (e.g., data.xml which contains a collection of all the indiviual data flows) and the last one (structure.xml) contains the data structure definition:
![image](https://github.com/user-attachments/assets/f1662fca-be8b-4cc3-adaa-f52dc0916d23)

If you open the structure.xml file, you'll see all the information that is necessary for the tool to visualize the data set .

First of all you'll see a description for the data flows contained in the source:
![image](https://github.com/user-attachments/assets/38b64e06-3647-43db-98c3-739676fb04aa)
and a mapping of the codes for each flow to the corresponding name:
![image](https://github.com/user-attachments/assets/3934e26b-4eff-4fb7-bfb7-07c07cf9d87d)

For each of the flows, there will be a component of the data structure `DataStructureComponents`:
![image](https://github.com/user-attachments/assets/f2496e67-5b0b-4c9a-aa17-11f1b7c73e27)
Here you'll see the list of `DimensionList`, the list of `AttributeList` and the `MeasureList` for each flow. 

In this case we have 4 dimensions (AREA, SEGMENT, POWERTRAIN, YEAR).
![image](https://github.com/user-attachments/assets/71094743-eaa5-447b-b609-9a198e1d68d7)
These four dimensions should be displayed and for the user to choose in any of the dimension of the view (rows, columns, filters):
<img width="212" alt="image" src="https://github.com/user-attachments/assets/5db42236-3a62-408e-8f9e-7bc4a0be5e92">

Further, we only have one `Attribute` called UNIT_MEASURE. This attribute should be displayed in the context menu:
![image](https://github.com/user-attachments/assets/44ef870b-64a0-4a38-ba51-f662e3b5ee2d)
In the example you have been working on, this would have been populated also with Source, Primary source and and the Metadata description.

Finally, you'll see the `Measure` (or `Indicator` ) for this data flow. In the case of the screenshot this would be "SEC".
The user should be able to select among the flows under the "Value" filter:
![image](https://github.com/user-attachments/assets/cfc0b3d1-6b36-4873-8319-8ca73d290cbe)

I hope this helps!

CC: @khaeru please add/correct if necessary

**Comment by luccasmmg** [comment] 2024-11-12 15:49
Doesnt this mean that every since point in the table will have the same tooltip metadata? Given that 'Unit of measure', 'Primary Source'  etc will always be the same 

![image](https://github.com/user-attachments/assets/7e416e98-3883-4fdb-bb82-170e8dced380)

**Comment by luccasmmg** [comment] 2024-11-12 15:51
Essentially what you want is for me to grab the columns from the `structure.xml` instead of the actual sql database 
![image](https://github.com/user-attachments/assets/81acf14a-ac05-45b9-a3c7-040c5171a26c)

**Comment by luccasmmg** [comment] 2024-11-12 15:52
I'm not sure if i understand the point here, basically you mean that using the gfei dataset as an example, you want the user to only have the option `SEC` in that dropdown?

![image](https://github.com/user-attachments/assets/5d931788-9cc3-4676-887b-4a4c8e1bdc2b)

**Comment by nicolas-becker** [comment] 2024-11-12 16:57
> Doesnt this mean that every since point in the table will have the same tooltip metadata? Given that 'Unit of measure', 'Primary Source' etc will always be the same

In this case it would probably be the same for each data point from the same flow, yes.

> Essentially what you want is for me to grab the columns from the structure.xml instead of the actual sql database

The structure.xml will indicate which columns to grab as dimensions, yes.

> I'm not sure if i understand the point here, basically you mean that using the gfei dataset as an example, you want the user to only have the option SEC in that dropdown?

In the gfei data set we have 4 different measures, one for each data flow (SEC, WT, FP, REG). The dropdown should thus contain these 4 options, or but displaying the name corresponding to each of these codes:

> and a mapping of the codes for each flow to the corresponding name:
> image

**Comment by luccasmmg** [comment] 2024-11-12 17:24
@nicolas-becker why the raw data for gfei doesnt have the correct columns?
https://zenodo.org/records/14046031/files/supplementary_information_GFEI2023_TDC.xlsx?download=1
Instead of AREA we have CountryISO3, or instead of FP we have `footprint_m2` it doesnt seem like there is a way to go from the description in `structure.xml` to the columns in the raw data

**Comment by nicolas-becker** [comment] 2024-11-12 17:55
Hi @luccasmmg in this case the data you are pointing to is not the SDMX converted data. Please have a look at the sdmx.zip file that is provided on the page:

> I will refer to the [SDMX version of the GFEI data set](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzenodo.org%2Frecords%2F14046031&data=05%7C02%7Cnicolas.becker%40giz.de%7C3362a9899ee345e6ea9608dcfe682a77%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C638664970564651154%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=BnlKvG2B7QlhZBjkSrpl3h4GcjpONwG3%2F%2BzbMr82%2BqE%3D&reserved=0) again. Here you'll find a zip file containing 6 XML files.

**Comment by Uchechukwu-Onye-Igbo** [comment] 2024-11-14 13:51
> Hi @luccasmmg in this case the data you are pointing to is not the SDMX converted data. Please have a look at the sdmx.zip file that is provided on the page:
> 
> > I will refer to the [SDMX version of the GFEI data set](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzenodo.org%2Frecords%2F14046031&data=05%7C02%7Cnicolas.becker%40giz.de%7C3362a9899ee345e6ea9608dcfe682a77%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C638664970564651154%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=BnlKvG2B7QlhZBjkSrpl3h4GcjpONwG3%2F%2BzbMr82%2BqE%3D&reserved=0) again. Here you'll find a zip file containing 6 XML files.

hello @luccasmmg please take a look at this

**Comment by nicolas-becker** [comment] 2024-11-14 14:26
Hi @Uchechukwu-Onye-Igbo, understood. Please work on the documentation for us to further adapt this to out needs in the future. Please let me know when this is ready for me to close the issue. Thanks

**Comment by Uchechukwu-Onye-Igbo** [comment] 2024-11-14 14:27
> Hi @Uchechukwu-Onye-Igbo, understood. Please work on the documentation for us to further adapt this to out needs in the future. Please let me know when this is ready for me to close the issue. Thanks

Yes, the documentation is in the works. Cc @luccasmmg

**Comment by nicolas-becker** [comment] 2024-11-28 16:56
@Uchechukwu-Onye-Igbo kindly flag when the docs are ready and please provide a link for me to check. Thank you

**Comment by luccasmmg** [comment] 2024-11-28 17:17
@nicolas-becker https://github.com/transport-data/tdc-data-portal/tree/main/docs/technical-documentation#data-explorer

**Comment by nicolas-becker** [comment] 2024-11-28 17:26
Thanks @luccasmmg I see that you also included some guidance of how to include a data structure file in the settings

**Closed** 2024-11-28 17:26 UTC

**Comment by luccasmmg** [comment] 2024-11-28 17:27
@nicolas-becker yeah, its basically a high level plan of how i would do it if it was me implementing
