### ISSUE TITLE
Ingest data from the TDC data sources into the portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#166] opened 2024-10-18 09:45 UTC
As a user of the TDC portal, I want the data from the priority TDC data sources to live in the portal so that I can access and preview the data directly through the portal.

The sources to ingest are:
- JRC-IDEES (Already handled by @Mikanebu) 40% only, but will finish it
- EUROSTAT (by @luccasmmg)
- GFEI (by @luccasmmg)

## Tasklist 
- [x] Prepare ingestion script for JRC source
- [x] Prepare ingestion script for GFEI
- [x] Prepare ingestion script for EUROSTAT
- [x] Publish all 3 sources to our data portal
- [x] Setup Github CI/CD for running on regular basis

## Acceptance Criteria
Given that I am interested in a data from any of the priority sources on the TDC portal,
- [x] I can preview and interact with the data directly in the portal
- [x] I can download the full data directly from the portal without having to be redirected out of the portal
- [x] Data will be updated on regular basis with keeping previous versions of the resource

**Comment by Verena205** [comment] 2024-10-23 12:07
The other ones should be Eurostat (https://tdc-data-portal.vercel.app/search?data_provider="EUROSTAT") and GFEI data --> @khaeru will provide more information on this

**Comment by Verena205** [comment] 2024-10-24 07:28
The GFEI is related to the #17  
The dataset is yet to be included in the website

**Comment by khaeru** [comment] 2024-10-30 09:00
- The original GFEI data is at https://doi.org/10.5281/zenodo.10148348.
- We have code at https://github.com/transport-data/gfei-2023 that converts these to SDMX.
- @PierpCazzola or his collaborator Leonardo Paoli will be updating the Zenodo record to include the converted SDMX files; hopefully in the next week or so.
- IMHO this data source should not be special-cased; rather we need a general-purpose capability to ‘ingest’ any record from Zenodo and similar permanent archives to a corresponding TDC CKAN record. This could involve:
  - Transforming Zenodo metadata to TDC metadata.
  - Displaying a clear link to the original Zenodo record.
  - Either mirroring the files, or linking to the files in their original location. (I am not sure what value is added by mirroring.)
  - Monitoring and refreshing the TDC CKAN record as the Zenodo record is updated.

**Comment by luccasmmg** [comment] 2024-10-30 12:23
@khaeru im 99% that is not the case but just want to make it clear, this general purpose action where we could provide any random url from Zenodo and create ckan datasets based on that, would not require us to convert the data into SDMX format, since im assuming thats quite dependant on the shape of the file

**Comment by nicolas-becker** [comment] 2024-11-06 17:36
Hi @luccasmmg & @Mikanebu  , the [SDMX version of the GFEI data](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzenodo.org%2Frecords%2F14046031&data=05%7C02%7Cnicolas.becker%40giz.de%7C3362a9899ee345e6ea9608dcfe682a77%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C638664970564651154%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=BnlKvG2B7QlhZBjkSrpl3h4GcjpONwG3%2F%2BzbMr82%2BqE%3D&reserved=0) was shared with us today. 

Regarding your last comment, the general-purpose capability of ingesting data sources from Zenodo proposed by @khaeru (please correct me if I am wrong) is unrelated to it being SDMX formatted or not, as you noticed correctly. The SDMX conversion is rather related to the capability of providing a preview of the data on our platform and to further process/merge it with similarly formatted data sources. Therefor, you can use this SDMX data source as a use case to test the tabular preview of the `TDC Formatted` data (#171).

**Comment by Uchechukwu-Onye-Igbo** [comment] 2024-11-07 13:38
Hello @nicolas-becker and @khaeru 

You would recall we agreed to ingest three data sources: JRC-IDEES, EUROSTAT, and GFEI. Additionally, since the GFEI source has a version SDMX format, we will include it as a second resource - just like you said we would in the call yesterday.

cc @Mikanebu @luccasmmg

**Comment by nicolas-becker** [comment] 2024-11-07 14:52
Hi @Uchechukwu-Onye-Igbo , yes this is what we agreed on. But if you add this sdmx version as a second resource, it would still be visualized in the dataset preview, right? This is why we have the following dropdown menu:

![image](https://github.com/user-attachments/assets/75a4657d-490b-4315-8f75-5fce4bb0057c)

My comment was refering to the question of @luccasmmg , who is implementing the visualization of SDMX compliant data (or TDC Formatted data). The idea is that this dataset could be used by him to test this functionality.

**Comment by Uchechukwu-Onye-Igbo** [comment] 2024-11-07 15:05
> Hi @Uchechukwu-Onye-Igbo , yes this is what we agreed on. But if you add this sdmx version as a second resource, it would still be visualized in the dataset preview, right? This is why we have the following dropdown menu:
> 
> ![image](https://github.com/user-attachments/assets/75a4657d-490b-4315-8f75-5fce4bb0057c)
> 
> My comment was refering to the question of @luccasmmg , who is implementing the visualization of SDMX compliant data (or TDC Formatted data). The idea is that this dataset could be used by him to test this functionality.
> 
> 

Okay. @luccasmmg kindly take a look on this comment and revert to @nicolas-becker

**Comment by nicolas-becker** [comment] 2024-11-26 08:57
Hi @Mikanebu I have a question related to the ingested data. The datasets you've ingested or integrated appear without a contributor. Is this always the case, when adding the data programmatically? 

Usually, when a user creates a dataset (at least via the frontend), the user will appear as contributor. So if we plan to update the data sets, e.g. the names or add topics or keywords, our names will appear as contributors, right?

**Comment by Mikanebu** [comment] 2024-11-26 13:16
Hi @nicolas-becker! 
Regarding 1st point: Since `contributors` is not required field, we did not pass it during our programmatically data upload. 
It is just another metadata field that can be filled as in documentation https://github.com/transport-data/tdc-data-portal/tree/main/docs/metadata-schema#contributors
Regarding 2nd point: You are right, once user updates dataset, contributor's field will be updated by that user automatically.

**Comment by Mikanebu** [comment] 2024-11-26 13:47
Also, if you check package from api, it has `"creator_user_id": "50bb4200-615b-4921-a8da-58f9d53ad9d0" `, but contributors was missing in the beginning, then after update, contributors added(updated with different user). You can see more information here 
https://ckan.tdc.dev.datopian.com/api/3/action/package_show?id=freight-transport-activity-water-jrc-idees

**Comment by khaeru** [comment] 2024-11-27 19:55
Sorry to jump in here with a *non sequitur*, but I am looking into the ingestion scripts and resulting CKAN packages that are created by them. Zooming in on one from OICA in particular: https://portal.transport-data.org/OICA/2023-production-statistics —I see:

> License
>
> [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/)

I don't see any script for OICA in the directory that was mentioned ([this one](https://github.com/transport-data/tdc-data-portal/tree/486872864285c3a225fbdbec56a393fb29fdd0f5/src/ckanext-tdc/ckanext/tdc/data-ingestion)). Maybe it hasn't been committed yet.

In any case, the OICA website actually doesn't clearly give a license for these data on [the specific page](https://www.oica.net/category/production-statistics/2023-statistics/), but their [general ‘Legal Notice’ page](https://www.oica.net/legal-notice/) has (in French) a very strict warning:

> Tous droits de reproduction sont réservés, y compris pour les documents téléchargeables. Les droits d’utilisation, de reproduction et de diffusion sont strictement réservés à l’OICA. La reproduction de tout ou partie de ce site sur un support électronique quel qu’il soit est formellement interdite sauf autorisation expresse de l’OICA.

> All reproduction rights are reserved, including for downloadable documents. The rights of use, reproduction and distribution are strictly reserved for OICA. **The reproduction of all or part of this site on any electronic medium whatsoever is strictly prohibited without the express authorization of OICA.**

In other words, these data are *not* CC-BY-4.0 licensed.

So to be clear, in this OICA case or in general, it is very important that we do not:
1. Republish data where we don't have permission. I can't find any mention here or elsewhere on the repo that we asked for and got that permission from OICA. If I missed it we need to record so more clearly.
2. Assign a license to data that is different from the one assigned by the original upstream provider.

Doing either of these could land TDCI participants in legal trouble; but worse than that it could lead to an antagonistic and unproductive relationship with data providers. Both would hinder TDCI's mission.

Until and unless we get express permission, the most we can do in such cases is include 1 or more direct URL(s) to the provider's own site. (I think it would be a good feature to display (based on a tag, maybe) a notice like, “Due to the copyright and licence terms of the data provider, TDCI cannot mirror the data files; please follow the link(s) to access the data.” But if not, it's okay.)

I checked the three other providers for which there *are* scripts (JRC, GFEI, and Eurostat) and confirmed they do, in fact, use CC-BY-4.0 licenses as shown in the CKAN metadata. But we will need to look for and correct any other mistakes like this OICA one before the site can be launched.

**Comment by Mikanebu** [comment] 2024-11-28 09:51
> Hi @Mikanebu , I see thank you.
> 
> > You can see more information here
> > https://ckan.tdc.dev.datopian.com/api/3/action/package_show?id=freight-transport-activity-water-jrc-idees
> 
> So this example would correspond to this dataset on the frontend: https://tdc-data-portal.vercel.app/test123/freight-transport-activity-water-jrc-idees. So you've added keywords, and your name was added as contributor. Is there a way for us to avoid our names appearing in the ingested datasets when updating the datasets? The reason I am asking is that this would probably mess up the citations, which I asked Luccas to use the contributors as authors. I wouldn't want that our names appear as authors of these third-party data sources in the citations

@nicolas-becker This part regarding fields we need to discuss with DEV team, and @demenech Can you add your input here pls?

**Comment by Mikanebu** [comment] 2024-11-28 10:02
Dear @khaeru ! The place you are looking for OICA script is not there. You are checking [data-ingestion](https://github.com/transport-data/tdc-data-portal/tree/486872864285c3a225fbdbec56a393fb29fdd0f5/src/ckanext-tdc/ckanext/tdc/data-ingestion) folder, it has only 3 sources which are in description: 
* JRC-IDEES
* EUROSTAT
* GFEI.

All other 16 sources's script are located here in [data-integration](https://github.com/transport-data/tdc-data-portal/tree/486872864285c3a225fbdbec56a393fb29fdd0f5/src/ckanext-tdc/ckanext/tdc/data-integration) folder.
For particular IOCA datasets, starts here https://github.com/transport-data/tdc-data-portal/blob/486872864285c3a225fbdbec56a393fb29fdd0f5/src/ckanext-tdc/ckanext/tdc/data-integration/process_tdc.py#L1939
I do not remember in which discussion, but for all datasets from this [spreadsheet](https://docs.google.com/spreadsheets/d/1L-Xsql6DZPAz-9HzmvLB6ct_MH7aA9fd/edit?gid=1966433740#gid=1966433740), we added [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/) license. In the spreadsheet, we did not included some of them, because you said that they need to be agreed with providers, the rest we added.
Since we have already uploaded all of them, we can use `package_patch` command to remove all the licenses to keep on 3 sources which are in data ingestion folder. Let me know how to proceed. 
cc @Uchechukwu-Onye-Igbo

**Comment by Mikanebu** [comment] 2024-11-28 12:30
@khaeru The easiest and simple solution here is to make datasets private, so it will not show up on the portal unless we get some proper permission.

**Comment by nicolas-becker** [comment] 2024-11-28 16:44
@Mikanebu I just tried to set the datasets to private but this is not working, as it seems like the sysadmin rights were not fully granted, as mentioned in issue #180.

> Until and unless we get express permission, the most we can do in such cases is include 1 or more direct URL(s) to the provider's own site. (I think it would be a good feature to display (based on a tag, maybe) a notice like, “Due to the copyright and licence terms of the data provider, TDCI cannot mirror the data files; please follow the link(s) to access the data.” But if not, it's okay.)

Based on the important hint provided by @khaeru the required action would be to 
1) set the OICA sets on private
2) delete the files in the download page
3) adapt the licence. Probably "Licence not Specified"
4) clearly highlight the link to OICAs website. I saw that you provided the URL in the respective field, but I can't see it reflected on the dataset metadata or resource page.
5) after 2, 3 and 4 we can publish the dataset again.

Also I am noticing that you provided this source in the dataset description: UNCTAD ( unctad.org/en/Pages/statistics.aspx ). Where does this link originate from? I was not able to locate it on the spreadsheet.

**Comment by Mikanebu** [comment] 2024-11-29 05:24
@nicolas-becker Could you share your username? From sysadmin list I can see this username `nico_becker_ar`, is this correct?

**Comment by Mikanebu** [comment] 2024-11-29 05:48
@demenech Could you pls help me with point 4 in latest Nikolas's comment `clearly highlight the link to OICAs website. I saw that you provided the URL in the respective field, but I can't see it reflected on the dataset metadata or resource page.`. Seems like we are not displaying some fields. I think it is `URL` field, in this field we use OICA dataset url. cc @nicolas-becker

**Comment by nicolas-becker** [comment] 2024-11-29 08:47
> @nicolas-becker Could you share your username? From sysadmin list I can see this username `nico_becker_ar`, is this correct? Re description, this is my fault, I updated description, thanks for catching this. Also updated licenses to not specified, datasets to private, and updated data integration script accordingly. Since you are sysadmin, you have all privileges to do anything in the portal.

Hi @Mikanebu thanks for the edit. I have the sysadmin access now and can enter the edit page. Still it is not possible for me to make any changes to the dataset, the Submit button seems to be disabled.

**Comment by osahon-okungbowa** [comment] 2024-11-29 08:56
> > @nicolas-becker Could you share your username? From sysadmin list I can see this username `nico_becker_ar`, is this correct? Re description, this is my fault, I updated description, thanks for catching this. Also updated licenses to not specified, datasets to private, and updated data integration script accordingly. Since you are sysadmin, you have all privileges to do anything in the portal.
> 
> Hi @Mikanebu thanks for the edit. I have the sysadmin access now and can enter the edit page. Still it is not possible for me to make any changes to the dataset, the Submit button seems to be disabled.

@demenech @Gutts-n @luccasmmg please look into this inability to edit a dataset issue 

cc @Uchechukwu-Onye-Igbo

**Comment by khaeru** [comment] 2024-11-29 09:09
Thanks all for understanding the issue with incorrect licenses 🙏🏾

> All other 16 sources's script are located here in [data-integration](https://github.com/transport-data/tdc-data-portal/tree/486872864285c3a225fbdbec56a393fb29fdd0f5/src/ckanext-tdc/ckanext/tdc/data-integration) folder.
> For particular IOCA [sp?] datasets, starts here

Okay, thanks for pointing out this other directory. I must have missed the reference to it during the previous call.

It makes me a little sad to see that (a) new code was written for this that duplicates [code we already have](https://docs.transport-data.org/en/latest/oica.html), and (b) this script has 20000 lines (!) that we will have to digest and somehow maintain. I think we could have avoided creating so much technical debt and future work.

In any case, I've updated transport-data/tools#34 for TDCI to take up later.

**Comment by Mikanebu** [comment] 2024-11-29 10:39
@khaeru We removed duplicated datasets(JRC, Eurostat and GFEI) from data-integration section.

**Comment by Uchechukwu-Onye-Igbo** [comment] 2024-12-02 08:10
> [@khaeru](https://github.com/khaeru) We removed duplicated datasets(JRC, Eurostat and GFEI) from data-integration section.

@khaeru and @nicolas-becker

**Comment by khaeru** [comment] 2024-12-02 09:07
To be clear, I raised two issues in this thread:
1. The CKAN records created by the code, particularly the OICA ones. I think the expedient chosen of setting the OICA ones private is fine.
2. The quality of the code itself, pointed out by the responses to my initial comments.

Whether or not there were duplicate CKAN records (1) (I didn't see or mention duplicates, only the license issue), the code (2) in the latest commit on `main` still has the version of process_tdc.py with 424 (!) largely identical functions and >20000 lines of code: https://github.com/transport-data/tdc-data-portal/blob/486872864285c3a225fbdbec56a393fb29fdd0f5/src/ckanext-tdc/ckanext/tdc/data-integration/process_tdc.py#L19756-L19802

I don't think anyone can credibly argue that this code is maintainable, which is why I said it was disappointing to see it. But I also recognize it is too late in the process to do anything about this, so we will just have to accept/receive it and deal with the technical debt later, i.e. turning it into something that *can* be maintained.

**Comment by Mikanebu** [comment] 2024-12-02 11:24
For example, this code extracts all the necessary metadata for each dataset, then you can update that created json file and use `package_patch` command to update required fields, or use `package_update`, to get entire metadata.  See more details here https://docs.ckan.org/en/2.10/api/
```
import json
import requests

# CKAN API details
CKAN_BASE_URL = "https://your-ckan-instance-url/api/3/action"  # Replace with your CKAN instance URL
API_KEY = "your-api-key"  # Optional if the endpoint requires authentication

# Output JSON file
OUTPUT_FILE = "ckan_packages.json"

# Headers for API requests
headers = {
    "Authorization": API_KEY,  # Add API key if authentication is required
}

def fetch_all_packages():
    # Step 1: Get all package IDs
    package_list_url = f"{CKAN_BASE_URL}/package_list"
    response = requests.get(package_list_url, headers=headers)
    response.raise_for_status()  # Raise an error if the request fails
    package_ids = response.json().get("result", [])  
    all_package_details = []

    # Step 2: Fetch details for each package
    for package_id in package_ids:
        package_show_url = f"{CKAN_BASE_URL}/package_show"
        params = {"id": package_id}
        package_response = requests.get(package_show_url, headers=headers, params=params)
        
        if package_response.status_code == 200:
            package_data = package_response.json().get("result", {})
            all_package_details.append(package_data)
        else:
            print(f"Failed to fetch details for package: {package_id} (Status Code: {package_response.status_code})")

    # Step 3: Save the results to a JSON file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(all_package_details, f, indent=4, ensure_ascii=False)
    
    print(f"Package details saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    fetch_all_packages()
```

**Comment by nicolas-becker** [comment] 2024-12-09 12:28
@luccasmmg 

> Seems like it was just a hiccup on the datapusher, i just uploaded again to the datastore and its working

Thank you. It is displaying the data correctly now, but still only for 2 of th 3 CSVs in that example.

Regarding the typecast and filtering, I understand. So basically all columns are treated equally, except the dates. Thanks for the explanation.

**Closed** 2024-12-12 08:11 UTC
